#!/bin/bash
#SBATCH -J Aphid-loop
#SBATCH --mem=400gb
#SBATCH --nodes=1
#SBATCH --ntasks=50
#SBATCH --time=48:00:00
#SBATCH --error=error/Aphids.e%j
#SBATCH --output=log/Aphids.o%j

### Gloabl variables
threads=50

### Build initial SRS list with dataset command

source /users/j/o/jotorr/enviro/mamba/micro/etc/profile.d/micromamba.sh

micromamba activate datasets

if [ -f NCBI-refrence-info.done ]; then
        echo "Reference info already exists, skipping dataset retrieval"
else

    datasets summary genome --reference --assembly-version 'latest' --as-json-lines taxon "Aphididae" | \
    dataformat tsv genome --fields accession,organism-name,assminfo-bioproject,assminfo-biosample-ids-db,assminfo-biosample-ids-label,assminfo-biosample-ids-value \
    > NCBI-refrence-info.tsv

    touch NCBI-refrence-info.done
fi

micromamba deactivate

source /users/j/o/jotorr/enviro/mamba/micro/etc/profile.d/micromamba.sh

micromamba activate entrez

cd /proj/parkerlab/users/jotorr/refrence-aphids

### Download SRR accessions from NCBI SRS numbers from the previous datasets command and make a list of them 

listy=$(grep "SRA" /proj/parkerlab/users/jotorr/refrence-aphids/target/NCBI-refrence-info.tsv | awk '{ print $NF }')

catter=(${listy})

echo "" > srr_list-1.txt

### Loop through the SRS numbers and get the corresponding SRR accessions and taxids, then save them in a list

if [ -f srr_list-1.txt ]; then
        echo "SRR list already exists, skipping SRR retrieval"
else

        echo "" > srr_list-1.txt

    for meow in ${catter[@]}; do
            srrl=$( \
            esearch -db "SRA" -query "${meow}" | \
            efetch -format docsum | \
            xtract -pattern Runs -element Run@acc )

            taxid=$( \
            esearch -db "SRA" -query "${meow}" | \
            efetch -format docsum | \
            xtract -pattern DocumentSummary -element Organism@taxid )

            echo ${taxid}@${srrl} >> srr_list-1.txt

    done

    touch srr_list-1.done

fi

### Loop through each taxid in the SRR list and download the corresponding fastq files using fasterq-dump, then save them in a taxid directory

micromamba deactivate

source /users/j/o/jotorr/enviro/mamba/micro/etc/profile.d/micromamba.sh

micromamba activate sra-tools

txlist=$( awk -F "@" '{ print $1 }' srr_list-1.txt | sort -u )

entry=( ${txlist} )

for id in ${entry[@]}; do

        if [ -f ${id}-unitigs/${id}-spades.done ]; then
        
                echo "SPAdes unitigs for taxid ${id} already generated, skipping entire taxid ${id}"

                continue
        fi

        mkdir ${id}
        srrs=$( grep "${id}" srr_list-1.txt | awk -F "@" '{ print $2 }' )
        if [ -f ${id}/${id}-download.done ]; then
                echo "SRR files for taxid ${id} already downloaded, skipping download"

        else
            for srr in ${srrs}; do
                    fasterq-dump ${srr} -O ${id} --threads ${threads}
            done
            touch ${id}/${id}-download.done
        fi
        # Concat mix of fastq and fasta files into one file for each taxid

        if [ -f ${id}/${id}-concat.done ]; then
                echo "SRR files for taxid ${id} already concatenated, skipping concatenation"
        else

            cat ${id}/*.fa* > ${id}/${id}.fastx

            touch ${id}/${id}-concat.done

        fi

        # Convert fastq fasta mix into fasta format
        # If the line starts with ">" then print it and set b to 1
        # if the line starts with "@" then split it by "@" and print ">" followed by the second element of the split and set b to 1
        # if the line starts with "+" then set b to 0 and a to 1, if the line does not start with ">" or "@" and b is 1 and a is 0 then print the line
        # at the end of each line set a to 0 so the @ lines adjacent to the + lines are not printed ( no false positives )

        if [ -f ${id}/${id}-concat-fasta.done ]; then
                echo "SRR files for taxid ${id} already converted to fasta, skipping conversion"
        else

            awk 'BEGIN{ b=0 ; a=0 ; }{ if ( $1 ~ /^>/ ) { print $0 ; b=1 } ;  if ( $1 ~ /^@/ ) { split($0, a, "@") ; print ">"a[2] ; b=1 } ; if ( $1 ~ /^+/ ) { b=0 ; a=1 } ; if ( $1 !~ /^>/ || $1 !~ /^@/ ) { if ( b == 1 && a == 0 ) { print $0 } } ; a=0 }' \
            
            ${id}/${id}.fastx > ${id}/${id}-all.fasta

            touch ${id}/${id}-concat-fasta.done

        fi




    ########## conitune writing code here ( everything else up top should be ready ) ##########

    ### Spades unitigging

        if [ -f ${id}/${id}-spades.done ]; then

                echo "SPAdes unitigs for taxid ${id} already generated, skipping SPAdes"

        else

                mkdir ${id}-unitigs

                spades-gbuilder \
                        ${id}/${id}-all.fasta \
                        ${id}-unitigs/${id}-all.unitigs \
                        --unitigs \
                        -k 55 \
                        -t ${threads} \
                        -tmp-dir /proj/parkerlab/users/pandora/tmp

                touch ${id}-unitigs/${id}-spades.done

        fi

        rm -rf ${id}/


done
